package com.linewell.www.dao;

import com.linewell.www.pojo.Test;
import com.linewell.www.pojo.TestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST
     *
     * @mbg.generated Sat Apr 07 09:20:40 CST 2018
     */
    long countByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST
     *
     * @mbg.generated Sat Apr 07 09:20:40 CST 2018
     */
    int deleteByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST
     *
     * @mbg.generated Sat Apr 07 09:20:40 CST 2018
     */
    int insert(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST
     *
     * @mbg.generated Sat Apr 07 09:20:40 CST 2018
     */
    int insertSelective(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST
     *
     * @mbg.generated Sat Apr 07 09:20:40 CST 2018
     */
    List<Test> selectByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST
     *
     * @mbg.generated Sat Apr 07 09:20:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") Test record, @Param("example") TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST
     *
     * @mbg.generated Sat Apr 07 09:20:40 CST 2018
     */
    int updateByExample(@Param("record") Test record, @Param("example") TestExample example);
}