package com.linewell.www.pojo;

public class Test {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.TEST_ID
     *
     * @mbg.generated Sat Apr 07 09:20:40 CST 2018
     */
    private String testId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.TEST_NAME
     *
     * @mbg.generated Sat Apr 07 09:20:40 CST 2018
     */
    private String testName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.TEST_ID
     *
     * @return the value of TEST.TEST_ID
     *
     * @mbg.generated Sat Apr 07 09:20:40 CST 2018
     */
    public String getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.TEST_ID
     *
     * @param testId the value for TEST.TEST_ID
     *
     * @mbg.generated Sat Apr 07 09:20:40 CST 2018
     */
    public void setTestId(String testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.TEST_NAME
     *
     * @return the value of TEST.TEST_NAME
     *
     * @mbg.generated Sat Apr 07 09:20:40 CST 2018
     */
    public String getTestName() {
        return testName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.TEST_NAME
     *
     * @param testName the value for TEST.TEST_NAME
     *
     * @mbg.generated Sat Apr 07 09:20:40 CST 2018
     */
    public void setTestName(String testName) {
        this.testName = testName;
    }
}